Repository lf-lang/reactor-c, pull requests merged in 2023-03, with the labels that each got.

#172 Split up functions of rti.c to rti_lib.c for reuse of functions.
  .github/workflows/ci.yml
  core/federated/RTI/CMakeLists.txt
  core/federated/RTI/rti.c
  core/federated/RTI/rti.h
  core/federated/RTI/rti_lib.c
  core/federated/RTI/rti_lib.h
Labels: refactoring

#178 Tracing federate interactions
  core/federated/RTI/CMakeLists.txt
  core/federated/RTI/message_record/message_record.c
  core/federated/RTI/rti.c
  core/federated/RTI/rti_lib.c
  core/federated/RTI/rti_lib.h
  core/federated/federate.c
  core/federated/net_util.c
  core/trace.c
  include/core/platform.h
  include/core/reactor_common.h
  include/core/trace.h
  lingua-franca-ref.txt
Labels: feature

#184 Various suggested updates for watchdogs branch
  core/reactor_common.c
  include/core/lf_types.h
  include/core/reactor_common.h
Labels: enhancement
