Repository lf-lang/reactor-c, pull requests merged in 2023-11, with the labels that each got.

#297 Use env command rather than /usr/bin/python3
  util/tracing/visualization/fedsd.py
Labels: enhancement, cleanup

#280 Bugfix in C decentralized execution with small after delays
  core/federated/federate.c
  core/threaded/reactor_threaded.c
  lingua-franca-ref.txt
Labels: bugfix

#303 Run Python tests in CI and revert #293
  .github/workflows/ci.yml
  lingua-franca-ref.txt
  python/lib/pythontarget.c
Labels: bugfix, ci

#250 Mentions of "unthreaded" replaced with "single-threaded"
  .github/workflows/ci.yml
  CMakeLists.txt
  core/CMakeLists.txt
  core/environment.c
  core/federated/RTI/CMakeLists.txt
  core/platform/arduino_mbed/ConditionWrapper.cpp
  core/platform/arduino_mbed/MutexWrapper.cpp
  core/platform/arduino_mbed/ThreadWrapper.cpp
  core/platform/lf_C11_threads_support.c
  core/platform/lf_POSIX_threads_support.c
  core/platform/lf_arduino_support.c
  core/platform/lf_linux_support.c
  core/platform/lf_macos_support.c
  core/platform/lf_nrf52_support.c
  core/platform/lf_os_single_threaded_support.c
  core/platform/lf_rp2040_support.c
  core/platform/lf_windows_support.c
  core/platform/lf_zephyr_clock_counter.c
  core/platform/lf_zephyr_clock_kernel.c
  core/platform/lf_zephyr_support.c
  core/reactor.c
  core/reactor_common.c
  core/threaded/reactor_threaded.c
  core/threaded/scheduler_GEDF_NP.c
  core/threaded/scheduler_NP.c
  core/threaded/scheduler_sync_tag_advance.c
  core/trace.c
  core/utils/semaphore.c
  include/core/environment.h
  include/core/lf_types.h
  include/core/platform.h
  include/core/platform/lf_arduino_support.h
  include/core/platform/lf_linux_support.h
  include/core/platform/lf_macos_support.h
  include/core/platform/lf_rp2040_support.h
  include/core/platform/lf_windows_support.h
  include/core/platform/lf_zephyr_support.h
  include/core/reactor.h
  include/core/threaded/scheduler.h
  include/core/trace.h
  lingua-franca-ref.txt
  util/tracing/Makefile
Labels: refactoring

#306 Priority queue refactoring
  core/federated/RTI/CMakeLists.txt
  core/tag.c
  core/utils/CMakeLists.txt
  core/utils/pqueue.c
  core/utils/pqueue_base.c
  core/utils/pqueue_tag.c
  docs/README.md
  include/core/utils/pqueue.h
  include/core/utils/pqueue_base.h
  include/core/utils/pqueue_tag.h
  test/general/utils/pqueue_test.c
Labels: enhancement, refactoring, cleanup

#309 Added return for non-void return function for arduino support
  core/platform/lf_arduino_support.c
Labels: bugfix
