Repository lf-lang/reactor-c, pull requests merged in 2023-12, with the labels that each got.

#311 Detect ZDC in RTI and issue PTAG only for nodes in ZDC
  core/federated/RTI/main.c
  core/federated/RTI/rti_common.c
  core/federated/RTI/rti_common.h
  core/federated/RTI/rti_local.c
  core/federated/RTI/rti_local.h
  core/federated/RTI/rti_remote.c
  core/federated/federate.c
  core/reactor.c
  core/reactor_common.c
  core/tag.c
  core/threaded/reactor_threaded.c
  core/trace.c
  core/utils/util.c
  include/core/environment.h
  include/core/federated/federate.h
  include/core/reactor.h
  include/core/tag.h
  include/core/trace.h
  include/core/utils/util.h
  test/src_gen_stub.c
Labels: enhancement, federated

#292 Make new directory under `federated` named `network`
  CMakeLists.txt
  core/CMakeLists.txt
  core/federated/CMakeLists.txt
  core/federated/RTI/CMakeLists.txt
  core/federated/network/CMakeLists.txt
  core/federated/network/net_util.c
  include/core/federated/network/net_common.h
  include/core/federated/network/net_util.h
  lingua-franca-ref.txt
Labels: refactoring

#315 Update lingua-franca-ref.txt to point to master
  lingua-franca-ref.txt
Labels: cleanup

#316 Handle messages arriving during initial STA wait
  core/threaded/reactor_threaded.c
Labels: bugfix

#318 Fix minimum spacing of actions and reference to freed event
  core/modal_models/modes.c
  core/reactor_common.c
  include/core/lf_types.h
  lingua-franca-ref.txt
Labels: bugfix, cleanup

#324 Fix LF_ASSERT
  core/CMakeLists.txt
  include/core/utils/util.h
Labels: bugfix
