Repository lf-lang/reactor-c, pull requests merged in 2024-02, with the labels that each got.

#345 Fixes to README
  core/federated/RTI/README.md
Labels: documentation

#351 Put a single event on the recycle queue initially to avoid runtime malloc
  core/reactor_common.c
Labels: enhancement

#331 Unit tests for the RTI and fix of bug revealed by test
  core/federated/RTI/rti_common.c
  lingua-franca-ref.txt
  test/RTI/rti_common_test.c
  test/Tests.cmake
Labels: bugfix, ci

#356 Extensive platform-specific tests no longer run in PRs
  .github/scripts/check-diff.sh
  .github/workflows/check-diff.yml
  .github/workflows/ci.yml
  core/platform/lf_zephyr_support.c
  lingua-franca-ref.txt
Labels: ci

#354 Further cleanup
  core/federated/RTI/main.c
  core/federated/RTI/rti_local.c
  core/federated/RTI/rti_local.h
  core/federated/federate.c
  core/lf_token.c
  core/modal_models/modes.c
  core/platform/lf_zephyr_support.c
  core/reactor.c
  core/reactor_common.c
  core/tag.c
  core/threaded/reactor_threaded.c
  core/threaded/scheduler_GEDF_NP.c
  core/threaded/scheduler_NP.c
  core/threaded/scheduler_adaptive.c
  core/threaded/scheduler_instance.c
  include/api/reaction_macros_undef.h
  include/api/schedule.h
  include/core/lf_types.h
  include/core/platform.h
  include/core/reactor.h
  include/core/reactor_common.h
  include/core/threaded/reactor_threaded.h
  include/core/threaded/watchdog.h
  lib/schedule.c
  lingua-franca-ref.txt
  python/include/pythontarget.h
  python/lib/pythontarget.c
  test/src_gen_stub.c
  util/sensor_simulator.c
  util/sensor_simulator.h
Labels: cleanup

#365 Add missing include to pythontarget.c
  python/lib/pythontarget.c
Labels: exclude

#374 Save trace file for RTI in abnormal termination
  core/federated/RTI/main.c
Labels: exclude
