Repository lf-lang/reactor-c, pull requests merged in 2024-01, with the labels that each got.

#320 Add an option for specifying the time interval of showing messages to the tracing visualizer
  util/tracing/trace_to_csv.c
  util/tracing/visualization/README.md
  util/tracing/visualization/fedsd.py
Labels: enhancement

#323 Various bugfixes and cleanups in the support for federated programs
  core/federated/RTI/CMakeLists.txt
  core/federated/RTI/main.c
  core/federated/RTI/message_record/message_record.c
  core/federated/RTI/message_record/message_record.h
  core/federated/RTI/message_record/rti_pqueue_support.h
  core/federated/RTI/rti_common.c
  core/federated/RTI/rti_common.h
  core/federated/RTI/rti_local.c
  core/federated/RTI/rti_remote.c
  core/federated/RTI/rti_remote.h
  core/federated/clock-sync.c
  core/federated/federate.c
  core/federated/network/net_util.c
  core/reactor.c
  core/reactor_common.c
  core/tag.c
  core/threaded/reactor_threaded.c
  core/threaded/scheduler_NP.c
  core/threaded/scheduler_sync_tag_advance.c
  core/trace.c
  core/utils/pqueue_tag.c
  core/utils/util.c
  include/core/environment.h
  include/core/federated/clock-sync.h
  include/core/federated/federate.h
  include/core/federated/network/net_common.h
  include/core/federated/network/net_util.h
  include/core/lf_types.h
  include/core/reactor.h
  include/core/reactor_common.h
  include/core/tag.h
  include/core/threaded/reactor_threaded.h
  include/core/trace.h
  include/core/utils/pqueue_tag.h
  include/core/utils/util.h
  lingua-franca-ref.txt
  test/general/utils/pqueue_test.c
  util/tracing/Makefile
  util/tracing/visualization/fedsd.py
Labels: enhancement, bugfix, federated

#336 Fix silly error in pretty printing time
  core/tag.c
Labels: bugfix

#340 Rename semaphore.h/c to lf_semaphore.h/c
  core/threaded/scheduler_GEDF_NP.c
  core/threaded/scheduler_NP.c
  core/utils/CMakeLists.txt
  core/utils/lf_semaphore.c
  include/core/threaded/scheduler_instance.h
  include/core/utils/lf_semaphore.h
Labels: bugfix
