Repository lf-lang/reactor-c, pull requests merged in 2024-12, with the labels that each got.

#498 Update trace_impl.c
  .github/workflows/ci.yml
  trace/impl/src/trace_impl.c
Labels: bugfix

#500 Enable flexpret
  .github/workflows/ci.yml
Labels: ci

#502 Update clang-format to version 19.1.5
  .github/workflows/clang-format.yml
  core/federated/federate.c
  include/core/utils/impl/hashmap.h
  include/core/utils/impl/pointer_hashmap.h
  tag/api/tag.h
Labels: enhancement, ci

#501 Python 3.11, 3.12, and 3.13 support
  .github/workflows/clang-format.yml
  core/federated/federate.c
  include/core/utils/impl/hashmap.h
  include/core/utils/impl/pointer_hashmap.h
  python/lib/modal_models/impl.c
  python/lib/python_port.c
  python/lib/python_tag.c
  python/lib/pythontarget.c
  tag/api/tag.h
Labels: enhancement, bugfix

#492 Subtract time with care for overflow
  core/tag.c
  core/threaded/reactor_threaded.c
  tag/api/tag.h
Labels: cleanup

#504 Do not exit if there is no timeout, fast is true, and keepalive is true
  core/threaded/reactor_threaded.c
Labels: bugfix

#453 Usage of 'fixed-size' integer types in RTI code
  core/federated/RTI/rti_remote.c
  core/federated/clock-sync.c
  core/federated/federate.c
  core/utils/util.c
  include/core/utils/util.h
Labels: bugfix, federated

#505 Refactoring of socket related functions to a separate socket_common.c
  core/federated/RTI/CMakeLists.txt
  core/federated/RTI/rti_remote.c
  core/federated/RTI/rti_remote.h
  core/federated/clock-sync.c
  core/federated/federate.c
  core/federated/network/CMakeLists.txt
  core/federated/network/net_util.c
  core/federated/network/socket_common.c
  include/core/federated/network/net_common.h
  include/core/federated/network/net_util.h
  include/core/federated/network/socket_common.h
Labels: refactoring

#507 Make reactor names available at runtime
  core/reactor_common.c
  include/api/reaction_macros.h
  include/api/reaction_macros_undef.h
  include/core/lf_types.h
  include/core/reactor.h
Labels: enhancement
