Repository lf-lang/reactor-c, pull requests merged in 2024-03, with the labels that each got.

#379 Fix for Clang error
  .github/workflows/check-diff.yml
  .github/workflows/ci.yml
  logging/api/logging_macros.h
Labels: bugfix, mac

#377 Change ADR_RQ to ADR_QR for correct line drawing in trace_svg.html
  util/tracing/visualization/fedsd.py
Labels: bugfix

#380 Use SI units in reporting human-readable time
  core/federated/RTI/rti_common.h
  core/federated/federate.c
  core/tag.c
  core/threaded/reactor_threaded.c
  tag/api/tag.h
Labels: documentation, enhancement

#381 Added lf_combine_deadline_and_level function for use by code generator
  core/reactor_common.c
  include/core/reactor_common.h
Labels: cleanup

#391 Fix tagged message length from int32_t to uint32_t
  core/federated/RTI/rti_remote.c
  core/federated/federate.c
  core/federated/network/net_util.c
  include/core/federated/network/net_common.h
Labels: bugfix

#392 Add address query reply message
  core/federated/RTI/rti_remote.c
  core/federated/federate.c
  include/core/federated/network/net_common.h
Labels: bugfix

#387 Enable all warnings and treat them as errors
  .gitignore
  core/CMakeLists.txt
  core/environment.c
  core/federated/RTI/rti_common.h
  core/federated/RTI/rti_remote.c
  core/federated/clock-sync.c
  core/federated/federate.c
  core/federated/network/net_util.c
  core/lf_token.c
  core/lf_utils.cmake
  core/reactor.c
  core/reactor_common.c
  core/tag.c
  core/threaded/reactor_threaded.c
  core/threaded/scheduler_GEDF_NP.c
  core/threaded/scheduler_NP.c
  core/threaded/scheduler_adaptive.c
  core/threaded/watchdog.c
  core/tracepoint.c
  core/utils/CMakeLists.txt
  core/utils/pqueue.c
  core/utils/pqueue_support.h
  core/utils/pqueue_tag.c
  core/utils/util.c
  include/core/federated/network/net_util.h
  include/core/lf_token.h
  include/core/threaded/reactor_threaded.h
  include/core/tracepoint.h
  include/core/utils/impl/hashmap.h
  lib/CMakeLists.txt
  lib/schedule.c
  lingua-franca-ref.txt
  logging/api/logging_macros.h
  low_level_platform/api/low_level_platform.h
  low_level_platform/api/platform/lf_POSIX_threads_support.h
  low_level_platform/api/platform/lf_nrf52_support.h
  low_level_platform/impl/CMakeLists.txt
  low_level_platform/impl/Platform.cmake
  low_level_platform/impl/src/lf_C11_threads_support.c
  low_level_platform/impl/src/lf_linux_support.c
  low_level_platform/impl/src/lf_macos_support.c
  platform/impl/CMakeLists.txt
  platform/impl/platform.c
  test/RTI/rti_common_test.c
  test/general/utils/hashmap_test.c
  test/src_gen_stub.c
  trace/impl/CMakeLists.txt
  trace/impl/include/trace_impl.h
  trace/impl/src/trace_impl.c
  util/tracing/trace_util.c
  util/tracing/trace_util.h
Labels: refactoring, cleanup
