Repository lf-lang/reactor-c, pull requests merged in 2024-09, with the labels that each got.

#479 Fix compiler warnings in Zephyr and FlexPRET support files
  core/threaded/reactor_threaded.c
  core/threaded/scheduler_GEDF_NP.c
  core/threaded/scheduler_NP.c
  core/threaded/scheduler_adaptive.c
  lingua-franca-ref.txt
  low_level_platform/api/platform/lf_atomic.h
  low_level_platform/api/platform/lf_zephyr_support.h
  low_level_platform/impl/src/lf_atomic_gcc_clang.c
  low_level_platform/impl/src/lf_atomic_irq.c
  low_level_platform/impl/src/lf_atomic_windows.c
  low_level_platform/impl/src/lf_flexpret_support.c
  low_level_platform/impl/src/lf_platform_util.c
  low_level_platform/impl/src/lf_zephyr_clock_kernel.c
  low_level_platform/impl/src/lf_zephyr_support.c
Labels: refactoring

#481 Point to master
  .github/workflows/ci.yml
  lingua-franca-ref.txt
Labels: cleanup, ci

#483 Improved formatting in Dockerfile
  core/federated/RTI/rti.Dockerfile
Labels: cleanup

#482 Fix action is_present field not being reset
  core/environment.c
  core/reactor_common.c
  include/core/environment.h
  lingua-franca-ref.txt
Labels: bugfix

#486 Various fixes to silence warnings on Windows
  core/environment.c
  core/threaded/reactor_threaded.c
  core/utils/lf_semaphore.c
  core/utils/util.c
  include/core/lf_token.h
  include/core/utils/lf_semaphore.h
  lingua-franca-ref.txt
  logging/api/logging_macros.h
  low_level_platform/impl/src/lf_atomic_windows.c
  low_level_platform/impl/src/lf_windows_support.c
  trace/impl/src/trace_impl.c
Labels: cleanup, windows

#478 lf_sleep and lf_nanosleep added to lf_patmos_support
  low_level_platform/impl/src/lf_patmos_support.c
Labels: feature, platform
