Repository lf-lang/reactor-c, pull requests merged in 2024-05, with the labels that each got.

#417 Fix race condition in lf_watchdog_stop
  core/threaded/watchdog.c
Labels: bugfix

#420 TracePluginProperty fixes
  core/CMakeLists.txt
  core/federated/RTI/main.c
  core/reactor_common.c
  include/core/tracepoint.h
  lib/CMakeLists.txt
  lingua-franca-ref.txt
  trace/api/CMakeLists.txt
  trace/api/trace.h
  trace/api/types/CMakeLists.txt
  trace/api/types/trace_types.h
  trace/impl/src/trace_impl.c
  util/tracing/Makefile
  util/tracing/codegen/CMakeLists.txt
  util/tracing/codegen/src/tracepoint_to_rs.c
  util/tracing/trace_util.c
Labels: bugfix

#427 Dont apply/subtract clock sync offset from NEVER/FOREVER
  core/federated/clock-sync.c
  core/tag.c
  tag/api/tag.h
Labels: bugfix

#428 Update trace-plugin API
  core/reactor_common.c
  trace/api/trace.h
  trace/impl/src/trace_impl.c
Labels: enhancement

#425 Fixed preprocessor directives for clock sync
  core/CMakeLists.txt
  core/clock.c
  core/federated/RTI/rti_remote.c
  core/federated/clock-sync.c
  core/reactor_common.c
  core/tag.c
  include/core/federated/clock-sync.h
  tag/api/tag.h
Labels: bugfix

#431 Zephyr: Reset sleeping semaphore and correctly check its return values
  low_level_platform/impl/src/lf_zephyr_clock_kernel.c
Labels: bugfix, zephyr

#412 Support for FlexPRET platform
  .github/workflows/ci.yml
  core/reactor.c
  core/reactor_common.c
  core/threaded/reactor_threaded.c
  core/utils/util.c
  low_level_platform/api/CMakeLists.txt
  low_level_platform/api/low_level_platform.h
  low_level_platform/api/platform/lf_arduino_support.h
  low_level_platform/api/platform/lf_flexpret_support.h
  low_level_platform/api/platform/lf_nrf52_support.h
  low_level_platform/api/platform/lf_rp2040_support.h
  low_level_platform/api/platform/lf_zephyr_support.h
  low_level_platform/impl/CMakeLists.txt
  low_level_platform/impl/src/lf_atomic_irq.c
  low_level_platform/impl/src/lf_flexpret_support.c
  platform/impl/CMakeLists.txt
Labels: feature

#435 Support for hyphens and underscores in rti host name
  core/federated/network/net_util.c
Labels: bugfix, RTI

#436 Let pthread detect if the cpu number is valid
  low_level_platform/impl/src/lf_linux_support.c
Labels: enhancement, schedulers

#437 Run one worker on main thread
  core/threaded/reactor_threaded.c
  low_level_platform/impl/src/lf_zephyr_support.c
Labels: enhancement

#344 Rp2040 multithreaded target support
  low_level_platform/api/CMakeLists.txt
  low_level_platform/api/platform/lf_rp2040_support.h
  low_level_platform/impl/CMakeLists.txt
  low_level_platform/impl/src/lf_rp2040_support.c
Labels: enhancement, feature

#433 Redesign of GEDF scheduler
  core/environment.c
  core/federated/federate.c
  core/reactor.c
  core/threaded/reactor_threaded.c
  core/threaded/scheduler_GEDF_NP.c
  core/threaded/scheduler_NP.c
  core/threaded/scheduler_adaptive.c
  core/threaded/scheduler_instance.c
  core/threaded/scheduler_sync_tag_advance.c
  core/utils/pqueue.c
  include/core/environment.h
  include/core/federated/federate.h
  include/core/lf_types.h
  include/core/threaded/reactor_threaded.h
  include/core/threaded/scheduler.h
  include/core/threaded/scheduler_instance.h
  include/core/threaded/scheduler_sync_tag_advance.h
  lingua-franca-ref.txt
  low_level_platform/api/low_level_platform.h
Labels: enhancement, schedulers, bugfix, cleanup

#440 Fix cmake syntax
  lingua-franca-ref.txt
  low_level_platform/impl/CMakeLists.txt
Labels: bugfix
