Repository lf-lang/reactor-c, pull requests merged in 2024-04, with the labels that each got.

#399 Update RTI dockerfile to match file layout change
  core/federated/RTI/rti.Dockerfile
  include/core/federated/network/net_common.h
Labels: bugfix, federated

#390 Refactoring of event queue
  core/environment.c
  core/federated/federate.c
  core/modal_models/modes.c
  core/reactor.c
  core/reactor_common.c
  core/threaded/reactor_threaded.c
  core/utils/pqueue.c
  core/utils/pqueue_base.c
  core/utils/pqueue_support.h
  core/utils/pqueue_tag.c
  include/core/environment.h
  include/core/lf_types.h
  include/core/reactor_common.h
  include/core/utils/pqueue.h
  include/core/utils/pqueue_base.h
  include/core/utils/pqueue_tag.h
  lib/schedule.c
Labels: refactoring

#400 Zephyr make kernel clock default + improvements
  low_level_platform/api/platform/lf_zephyr_board_support.h
  low_level_platform/api/platform/lf_zephyr_support.h
  low_level_platform/impl/CMakeLists.txt
  low_level_platform/impl/src/lf_zephyr_clock_counter.c
  low_level_platform/impl/src/lf_zephyr_clock_kernel.c
  platform/impl/CMakeLists.txt
Labels: enhancement, zephyr, mac

#407 Improve handling of timeouts when federates connect to RTI/each other
  core/federated/federate.c
  include/core/federated/federate.h
  include/core/federated/network/net_common.h
  tag/api/tag.h
Labels: enhancement, federated

#411 Proper handling of negative value passed in as the number of federates
  core/federated/RTI/main.c
Labels: bugfix

#355 Extend platform API with functions for setting thread scheduling policy, core affinity and priority + remove C11 as platform
  low_level_platform/api/low_level_platform.h
  low_level_platform/api/platform/lf_C11_threads_support.h
  low_level_platform/api/platform/lf_linux_support.h
  low_level_platform/api/platform/lf_macos_support.h
  low_level_platform/api/platform/lf_platform_util.h
  low_level_platform/impl/CMakeLists.txt
  low_level_platform/impl/src/lf_C11_threads_support.c
  low_level_platform/impl/src/lf_POSIX_threads_support.c
  low_level_platform/impl/src/lf_linux_support.c
  low_level_platform/impl/src/lf_macos_support.c
  low_level_platform/impl/src/lf_platform_util.c
  low_level_platform/impl/src/lf_unix_syscall_support.c
  low_level_platform/impl/src/lf_windows_support.c
  low_level_platform/impl/src/lf_zephyr_support.c
  low_level_platform/impl/src/platform_internal.c
  test/Tests.cmake
Labels: feature

#414 Fix clock sync init option
  core/CMakeLists.txt
  core/clock.c
  core/federated/clock-sync.c
  core/federated/network/net_util.c
  include/core/federated/clock-sync.h
Labels: bugfix

#415 Add fix to thread scheduling API
  low_level_platform/impl/src/lf_linux_support.c
  low_level_platform/impl/src/lf_platform_util.c
Labels: schedulers, bugfix

#416 Unit testing of thread scheduling API + additional fixes
  .github/workflows/unit-tests.yml
  .gitignore
  CMakeLists.txt
  README.md
  core/federated/RTI/CMakeLists.txt
  core/federated/RTI/README.md
  core/federated/RTI/test/rti_common_test.c
  low_level_platform/api/low_level_platform.h
  low_level_platform/impl/src/lf_linux_support.c
  low_level_platform/impl/src/lf_macos_support.c
  low_level_platform/impl/src/lf_windows_support.c
  low_level_platform/impl/src/lf_zephyr_support.c
  test/CMakeLists.txt
  test/Tests.cmake
  test/general/tag_test.c
  test/general/utils/hashmap_test.c
  test/general/utils/hashset_test.c
  test/general/utils/pqueue_test.c
  test/rand_utils.c
  test/scheduling/scheduling_api_test.c
  test/src_gen_stub.c
Labels: enhancement
