Repository lf-lang/reactor-c, pull requests merged in 2024-07, with the labels that each got.

#446 Fixes to prevent memory leaks in RTI
  core/federated/RTI/rti_remote.c
  core/utils/pqueue_tag.c
Labels: bugfix, RTI

#442 Fix support for NRF52
  lib/schedule.c
  low_level_platform/api/CMakeLists.txt
  low_level_platform/api/platform/lf_nrf52_support.h
  low_level_platform/impl/CMakeLists.txt
  low_level_platform/impl/src/lf_nrf52_support.c
  platform/impl/CMakeLists.txt
Labels: bugfix

#463 Fix adaptive scheduler
  core/reactor_common.c
  core/threaded/scheduler_adaptive.c
Labels: schedulers, bugfix, federated

#455 New Python functions `lf.package_directory()` and `lf.source_directory()`
  python/include/pythontarget.h
  python/lib/pythontarget.c
Labels: feature, python

#461 Better error messages when HMAC authentication is attempted by federates when RTI does not support it
  core/federated/RTI/rti_remote.c
  core/federated/federate.c
  include/core/federated/network/net_common.h
Labels: bugfix, security

#394 Transient federates: Use a priority queue sorted by tags to manage delayed grants.
  core/federated/RTI/main.c
  core/federated/RTI/rti_remote.c
  core/federated/RTI/rti_remote.h
  core/federated/federate.c
  core/tag.c
  core/threaded/reactor_threaded.c
  include/core/federated/federate.h
  include/core/federated/network/net_common.h
  include/core/utils/util.h
  tag/api/tag.h
Labels: enhancement, federated

#469 Immediate start of federates with STA offset under decentralized coordination
  core/threaded/reactor_threaded.c
Labels: enhancement

#432 Additional debug print-outs for watchdogs
  core/threaded/watchdog.c
Labels: bugfix, ci, mac

#471 Custom Serialization in Python Target
  python/include/pythontarget.h
  python/lib/pythontarget.c
Labels: enhancement
