Repository lf-lang/reactor-c, pull requests merged in 2025-01, with the labels that each got.

#509 Move CI to ubuntu-24.04
  .github/workflows/build-rti.yml
  .github/workflows/build-trace-tools.yml
  .github/workflows/unit-tests.yml
  lingua-franca-ref.txt
Labels: enhancement, ci

#510 Fix lingua-franca-ref
  lingua-franca-ref.txt
Labels: bugfix

#349 Downstream next event tag (DNET), a new signal for more efficient centralized federated execution
  core/federated/RTI/main.c
  core/federated/RTI/rti_common.c
  core/federated/RTI/rti_common.h
  core/federated/RTI/rti_local.c
  core/federated/RTI/rti_remote.c
  core/federated/RTI/rti_remote.h
  core/federated/RTI/test/rti_common_test.c
  core/federated/federate.c
  core/tag.c
  include/core/federated/federate.h
  include/core/federated/network/net_common.h
  tag/api/tag.h
  trace/api/types/trace_types.h
  util/tracing/visualization/fedsd.py
Labels: enhancement, feature, federated
