Repository lf-lang/reactor-c, pull requests merged in 2025-06, with the labels that each got.

#494 Stringify CMake command-line arguments before they are added as compile definitions
  core/CMakeLists.txt
  lingua-franca-ref.txt
Labels: enhancement

#533 Use of snprintf instead of vulerable sprintf for code security best practices.
  core/federated/network/socket_common.c
  trace/impl/src/trace_impl.c
  util/tracing/influxdb.h
Labels: cleanup

#532 Fix the documentation about localy building docs
  DOCUMENTATION.md
Labels: docs
